---
abstract: 'mimic Log::Log4perl in one single module'
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Tiny
provides:
  Log::Log4perl::Tiny:
    file: lib/Log/Log4perl/Tiny.pm
    version: 0.1
requires:
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
